### ISSUE TITLE
Blocked reactions question

### ISSUE THREAD

**Issue by dagl1** [Devlin-Moyer/macaw#4]
Hi Devlin,

I noticed that you handed in your Thesis (congrats!) and so might not be too busy, but I hope this finds you nontheless!
In trying to reduce the size/complexity of humanGem as much as possible, I have been using several methods and this lead me to a bit of a conundrum:

If I first apply fastCC to get a consistent network, followed by CycleFreeFlux FVA (using cobrapy's implementation) and removing any reactions that cannot carry flux (and also any Metabolites without reactions), I now should have properly removed any blocked reactions and unused/deadend metabolites. However when using Macaw on such a model I am still left with 1431 dead-end metabolites, 1600 reactions that cannot carry flux in either direction, and 1200 reversible that can only go in one direciton. 
While it is perfect if this is actually the case (in the sense that I can further reduce my model this way), it also is a bit strange to me as CycleFreeFlux + FVA should have already found all these if all are working correctly. Do you know of any reason why this would be (different definitions for the above mentioned terms (dead-ends etc)).

If there isn't a clear reason then I will look further into whether the CycleFreeFlux FVA properly removed all reactions (as it appears that it cannot fully remove fluxes due to loops, but this still requires more investigation). Otherwise, if there is a viable reason why after these steps it is still possible to find dead-ends and reactions that cannot carry flux, I am very eager to hear/learn about it!

**Comment by dagl1** [comment]
On further inspection it appears that dead_end_results includes reactions that can carry flux and are connected properly to exchange reactions. 
Using Human-gem1.17 I find that MAR03905 MAR03907 (boht irreversible) both have been marked to have MAM01796c as dead-end metabolite. However this metabolite is connected to the reversible transport reaction MAR05000 which allows transport to MAM01796e, this metabolite in turn is connected to the reversible exchange reaction MAR09099 and so MAM01796 can created/imported into the model. The other input metabolite is NAD+ or NADP+ which both are not marked for being a dead-end metabolite and this is all happening before dilution tests. 

This would leave any of the three products of MAR03905/MAR03907 to be problematic, however: these products are H+, NADP(H) and acetaldehyde. Here the latter feels like the most likely suspect, but MAM01249c is then properly connected through reversible reactions to the exchange reaction: MAR09242 (through MAR04948).

I can maximize flux through both MAR03905/MAR03907 with no problems (although not at the same time of course) see below.
>>> dead_end_results.head
<bound method NDFrame.head of       reaction_id  ... dead_end_test
0        MAR03905  ...     MAM01796c
1        MAR03907  ...     MAM01796c
2        MAR04097  ...            ok
3        MAR04099  ...            ok
4        MAR04108  ...            ok
...           ...  ...           ...
10122    MAR20110  ...            ok
10123    MAR20111  ...            ok
10124    MAR20112  ...            ok
10125    MAR20113  ...            ok
10126    MAR20114  ...            ok

**Maximizing MAR03905**
MAR03905, Flux: 1000.0 Formula: ethanol + NAD+ --> acetaldehyde + H+ + NADH
Metabolites: {<Metabolite MAM01249c at 0x2deeb71fe90>: 1.0, <Metabolite MAM01796c at 0x2deeb7a5fd0>: -1.0, <Metabolite MAM02039c at 0x2deeb7cfdd0>: 1.0, <Metabolite MAM02552c at 0x2deeb832990>: -1.0, <Metabolite MAM02553c at 0x2deeb832e10>: 1.0}
MAR03907, Flux: 0.0 Formula: ethanol + NADP+ --> acetaldehyde + H+ + NADPH
Metabolites: {<Metabolite MAM01249c at 0x2deeb71fe90>: 1.0, <Metabolite MAM01796c at 0x2deeb7a5fd0>: -1.0, <Metabolite MAM02039c at 0x2deeb7cfdd0>: 1.0, <Metabolite MAM02554c at 0x2deeb8331d0>: -1.0, <Metabolite MAM02555c at 0x2deeb833650>: 1.0}
MAR05000, Flux: -1000.0 Formula: ethanol <=> ethanol
Metabolites: {<Metabolite MAM01796c at 0x2deeb7a5fd0>: -1.0, <Metabolite MAM01796e at 0x2deeb7a6150>: 1.0}
MAR09099, Flux: -1000.0 Formula: ethanol <=> 
Metabolites: {<Metabolite MAM01796e at 0x2deeb7a6150>: -1.0}
MAR08756, Flux: 0.0 Formula: ethanol <=> ethanol
Metabolites: {<Metabolite MAM01796c at 0x2deeb7a5fd0>: -1.0, <Metabolite MAM01796x at 0x2deeb7a6090>: 1.0}
MAR09242, Flux: 1000.0 Formula: acetaldehyde <=> 
Metabolites: {<Metabolite MAM01249e at 0x2deeb7281d0>: -1.0}
MAR03905, Flux: 1000.0 Formula: ethanol + NAD+ --> acetaldehyde + H+ + NADH
Metabolites: {<Metabolite MAM01249c at 0x2deeb71fe90>: 1.0, <Metabolite MAM01796c at 0x2deeb7a5fd0>: -1.0, <Metabolite MAM02039c at 0x2deeb7cfdd0>: 1.0, <Metabolite MAM02552c at 0x2deeb832990>: -1.0, <Metabolite MAM02553c at 0x2deeb832e10>: 1.0}

**Maximizing MAR03907**
MAR03905, Flux: 0.0 Formula: ethanol + NAD+ --> acetaldehyde + H+ + NADH
Metabolites: {<Metabolite MAM01249c at 0x2deeb71fe90>: 1.0, <Metabolite MAM01796c at 0x2deeb7a5fd0>: -1.0, <Metabolite MAM02039c at 0x2deeb7cfdd0>: 1.0, <Metabolite MAM02552c at 0x2deeb832990>: -1.0, <Metabolite MAM02553c at 0x2deeb832e10>: 1.0}
MAR03907, Flux: 1000.0 Formula: ethanol + NADP+ --> acetaldehyde + H+ + NADPH
Metabolites: {<Metabolite MAM01249c at 0x2deeb71fe90>: 1.0, <Metabolite MAM01796c at 0x2deeb7a5fd0>: -1.0, <Metabolite MAM02039c at 0x2deeb7cfdd0>: 1.0, <Metabolite MAM02554c at 0x2deeb8331d0>: -1.0, <Metabolite MAM02555c at 0x2deeb833650>: 1.0}
MAR05000, Flux: -1000.0 Formula: ethanol <=> ethanol
Metabolites: {<Metabolite MAM01796c at 0x2deeb7a5fd0>: -1.0, <Metabolite MAM01796e at 0x2deeb7a6150>: 1.0}
MAR09099, Flux: -1000.0 Formula: ethanol <=> 
Metabolites: {<Metabolite MAM01796e at 0x2deeb7a6150>: -1.0}
MAR08756, Flux: 0.0 Formula: ethanol <=> ethanol
Metabolites: {<Metabolite MAM01796c at 0x2deeb7a5fd0>: -1.0, <Metabolite MAM01796x at 0x2deeb7a6090>: 1.0}
MAR09242, Flux: 1000.0 Formula: acetaldehyde <=> 
Metabolites: {<Metabolite MAM01249e at 0x2deeb7281d0>: -1.0}
MAR03905, Flux: 0.0 Formula: ethanol + NAD+ --> acetaldehyde + H+ + NADH
Metabolites: {<Metabolite MAM01249c at 0x2deeb71fe90>: 1.0, <Metabolite MAM01796c at 0x2deeb7a5fd0>: -1.0, <Metabolite MAM02039c at 0x2deeb7cfdd0>: 1.0, <Metabolite MAM02552c at 0x2deeb832990>: -1.0, <Metabolite MAM02553c at 0x2deeb832e10>: 1.0}
MAR04948, Flux: 1000.0 Formula: acetaldehyde <=> acetaldehyde
Metabolites: {<Metabolite MAM01249c at 0x2deeb71fe90>: -1.0, <Metabolite MAM01249e at 0x2deeb7281d0>: 1.0}

**Comment by Devlin-Moyer** [comment]
hmm I am seeing the same thing and agree that it should not be happening; I suspect that it is correctly recognizing that `MAR09099` is effectively irreversible (can only import and not export ethanol) but is making it irreversible in the wrong direction (which is a problem I remember having a long time ago that I thought I'd solved, so that's worrying)

**Comment by dagl1** [comment]
I have the loopless FVA run results and could (and probably should) already apply the extreme values (min/max) as bounds. If your suspicion is correct, blocked_reactions should then not show this behaviour at all right (I will test this on Monday then too)?

**Comment by Devlin-Moyer** [comment]
I realized that I had the dead-end test flip all reversible reactions that it found could only run in the reverse direction before making them irreversible, but it skipped exchange reactions when doing this to maintain the convention of positive fluxes through exchange reactions = export, but there's really no good reason to do that within the narrow context of the dead-end test, so I edited it to stop skipping exchange reactions when doing that, and it no longer flags `MAR03907` et al. as being dead-ends, so I think that fixes the problem. It also slightly changes the total number of dead-end reactions & metabolites that it finds in version 1.17 of Human-GEM, but not by a huge margin (1522 vs 1382 dead-end metabolites)
I'm gonna make sure this doesn't somehow break the dilution test before pushing this change tho

**Comment by Devlin-Moyer** [comment]
in theory (also in practice cuz I've tested this at least a few times), the dead-end test should flag exactly the same set of reactions as dead-ends as ordinary FVA would (but do it faster and provide more information on how the dead-ends connect to each other), so it's not clear to me why it was still apparently finding so many dead-ends in your models

**Comment by dagl1** [comment]
Could it not be entirely due to the fake-flagging? Indeed it shouldn't happen but hopefully your fix (once dilution test doesn't become compromised) will be good enough. If not I'll try to find/create a smaller toy model where it is more easily identifiable.

**Comment by Devlin-Moyer** [comment]
The dilution test still seems to work, so I pushed the change I made to the dead-end test and confirmed that it no longer flags these particular reactions

**Comment by dagl1** [comment]
Oh super (edit from the end of the message: I still appear to have problems), I just finished debugging some FVA related stuff, basically loopless FVA for some reason provides min/max fluxes that cannot be obtained when applying any type of minimization/maximization. I now got it down to: 
obtained reduced loopless reduced model with 8274 reactions and 5418 metabolites. This includes having set all bounds for things that can only go 1 way correctly, such as MAR03905 to only be positive. With the previous implementation (before your new PR), it actually increased the amount of values, which is quite interesting:

 - Found 1796 dead-end metabolites.
 - Found 2426 reactions incapable of sustaining steady-state fluxes in either direction due to these dead-ends.
 - Found 140 reversible reactions that can only carry steady-state fluxes in a single direction due to dead-ends

Either way with your new PR I still have the same problems (albeit that something definitely changed):
Out[1]: 
 - Found 1732 dead-end metabolites.
 - Found 2323 reactions incapable of sustaining steady-state fluxes in either direction due to these dead-ends.
 - Found 168 reversible reactions that can only carry steady-state fluxes in a single direction due to dead-ends.

  reaction_id                                  reaction_equation dead_end_test
0    MAR03905  MAM01796c + MAM02552c --> MAM01249c + MAM02039...     MAM01796c
1    MAR03907  MAM01796c + MAM02554c --> MAM01249c + MAM02039...     MAM01796c
2    MAR04097  MAM01252c + MAM01371c + MAM01597c --> MAM01261...            ok
3    MAR04099  MAM01252m + MAM01371m + MAM01597m --> MAM01261...            ok
4    MAR04108  MAM01257c + MAM01597c --> MAM01261c + MAM01334...            ok
print(f"Model reactions length: {len(model.reactions)}, metabolite length: {len(model.metabolites)}")
Model reactions length: 8274, metabolite length: 5418
print(f"bounds on MAR03905: {model.reactions.get_by_id('MAR03905').bounds}")
bounds on MAR03905: (0.0, 1000.0)

I am wondering if this has to do with something on my end

[model_Human-GEM_loopless_FVA_reduced_model_adjusted_bounds_no_unused_metabolites.json](https://github.com/user-attachments/files/19074933/model_Human-GEM_loopless_FVA_reduced_model_adjusted_bounds_no_unused_metabolites.json)
, so I attached the model as .json 

Edit:
It for instance also highlights:
print(dead_end_results.iloc[6])
reaction_id                                                   MAR04281
reaction_equation    MAM02039x + MAM02553x + MAM02819x <-- MAM02403...
dead_end_test                                      MAM02403x;MAM02819x

However when I check the 2 reactions involved with MAM02403x these are:
frozenset({<Reaction MAR03007 at 0x2b00ad22c90>, <Reaction MAR04281 at 0x2b008e40cd0>})
One of these can carry move MAM02403x into the x compartment, and the other can carry it out. When I apply flux maximization to the positive flux carrying one:

 ids = ["MAR03007", "MAR04281"]
    rxns = [model.reactions.get_by_id(id) for id in ids]
    # max flux through 3007
    model.objective = Zero
    rxns[0].objective_coefficient = 1
    model.objective.direction = "max"
    model.optimize()

I get: Out[11]: <Solution 1000.000 at 0x2b021216c10>

**Comment by dagl1** [comment]
I realised the model has some fluxes that could only go backwards (so lb of -1000 but ub of 0), which is the case for the MAR04281 in my edit of the previous post. Fixing this (switching bounds and coeficients), leads to a slightly changed outcome (which while explainable, should probably not happen either way): 
 - Found 1764 dead-end metabolites.
 - Found 1841 reactions incapable of sustaining steady-state fluxes in either direction due to these dead-ends.
 - Found 170 reversible reactions that can only carry steady-state fluxes in a single direction due to dead-ends.

The MAR04281 is now not in there anymore, but this leads me to believe the function still is having some issues. I noticed that the PR only was pertaining the flip_reactions utils (might there have been a change to another file that wasn't included accidentally?)

**Comment by Devlin-Moyer** [comment]
the dead-end test uses the `flip_reactions` function, so that was the change that I intended to make that prevents it from incorrectly labeling `MAR03905` et al. as dead-ends. I'm not sure I understand what the new problem is

**Comment by dagl1** [comment]
Sorry my bad, let me recap:
FVA produces some odd results in that there are reactionst that are said to have actual min/max fluxes, that cannot be obtained after removing unused fluxes (I think this has to do with the loopless part, there is some discussion about it on cobrapy). 

Knowing this I ran my own flux minimzation/maximization and further reduced the model to a set of reactions and metabolites with valid bounds. In doing so I accidentally left some reactions that could only go in backwards direction (my last post), which apparently leads to a change in the behaviour of find_blocked_reactions. 

Either way, running the model with your newly uploaded PR, I still got quite a lot of reactions/metabolites being flagged (including 3905 and 3907). However since you mentioned it seemed to work for you now, I wondered if it was either A) something on my end (hence why I provided the model), or B) you might have only commited/pushed one of the files you changed and not all (but you clarified it is not the latter). 

I hope it is just someting on my end (I added some logging and extra saving functions to MACAW, but cannot imagine that that would lead to this behaviour). I will do a full reinstall tomorrow, but otherwise if this still is the case, then I would say that the issue hasn't been fixed (or is in some weird way due to the further FVA filtering).

I hope that this clears up the issue (tl;dr, i still see 3905 showing up).

**Comment by dagl1** [comment]
I think this can be closed, as I have found the origin of the problems and this I think has nothing to do with Macaw anymore.
The model has several metabolites such as GTP/GDP/ATP in the mitochondria, that in loopless FVA are not actually possible to produce/consume (most likely due to the nature of how these are transported to the cytoplasm), and some such as GTP/GDP even lack cytoplasm<>extracellular transport reactions. 
I think loopless FVA get's some very odd results in these cases, as it will correctly identify carrying flux with loops (but due to the way cyclefreeflux breaks loops, it might be infeasible to still carry flux with a broken loop, and when infeasible cyclefreeflux starts having issues). Thus when I filter any reaction that could not carry flux in the loopless FVA, there are now reactions in this model that if another FVA would be ran, would be identified as not being able to carry fluxes at all. Removing those then leaves me with even more dead-end metabolites and reactions.

When I run blocked reactions on just fastCC filtered models, I (assumed to be correct) get:
 - Found 0 dead-end metabolites.
 - Found 0 reactions incapable of sustaining steady-state fluxes in either direction due to these dead-ends.
 - Found 1591 reversible reactions that can only carry steady-state fluxes in a single direction due to dead-ends.

And when I run it on the origal model I get:  
 - Found 1382 dead-end metabolites.
 - Found 1140 reactions incapable of sustaining steady-state fluxes in either direction due to these dead-ends.
 - Found 1597 reversible reactions that can only carry steady-state fluxes in a single direction due to dead-ends.

FastCC itself removed 1290 reactions (so slighty more than indicated by blocked reactions, but I believe that will be okay as I can imagine some reactions with odd stoichiometries on the border of consistent/inconsistent. 

Thus I think that my previous posts can be distilled into: Macaw now seems to work, but loopless FVA on these models does not (when not fixing the overall structure of model, as otherwise half the krebb cycle is suddenly impossible).

**Comment by Devlin-Moyer** [comment]
The problems with nucleotide transport into mitochondria that you describe may have been fixed in version 1.18 of Human-GEM https://github.com/SysBioChalmers/Human-GEM/issues/694
